//
//  EnterpriseDetailInteractor.swift
//  empresas-ios
//
//  Created by Thiago Lima on 24/10/20.
//  Copyright (c) 2020 ioasys. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EnterpriseDetailBusinessLogic {
    func getEnterprise() -> Enterprise?
}

protocol EnterpriseDetailDataStore {
    var enterprise: Enterprise? { get set }
}

class EnterpriseDetailInteractor: EnterpriseDetailBusinessLogic, EnterpriseDetailDataStore {
    var enterprise: Enterprise?
    
    func getEnterprise() -> Enterprise? {
        return enterprise
    }
}
